#普通数据配置
name: zhangsan

server.port: 8081

#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing


#行内对象配置
person2: {name: lisi,age: 25, addr:shanghai}

#配置数据、集合(普通字符串)
city:
  - beijing
  - tianjng
  - shanghi
  - chengdu

cities: [beijing,tianjing,shanghai]

#配置数据、集合(对象数据)

student:
  - name: tom
    age: 18
    addr: beijng
  - name: Lucy
    age: 20
    addr: tianjing

students: [{name: tom, age: 18, addr: beijing}, {name: Lucy,age: 17,addr: shanghai}]


#Map配置
map:
  key1: value1
  key2: value2